lang: EN
shortKeys:
  - command: Load
    key: F5
    modifier: Control, Shift 
  - command: Import
    key: F3
    modifier: Control, Shift
  - command: Edit
    key: F2
    modifier: Control, Shift
  - command: Up
    key: F4
    modifier: Control, Shift
  - command: Down
    key: F1
    modifier: Control, Shift

profiles:
